language: node_js
dist: xenial
os: linux
node_js:
  - node
  - lts/*
install:
  - yarn
script:
  - yarn production
deploy:
  strategy: git
  provider: releases
  cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    node_js: 'lts/*'
