name: NodeJS CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: [ ubuntu-latest, windows-latest, macos-latest]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

  steps:
    - name: Pulling Code
      uses: actions/checkout@v2
    - name: Use NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
